export const products = [
  { id: 1, name: "Studio Laptop", category: "Electronics", price: 900, quantity: 6, code: "SL" },
  { id: 2, name: "Wireless Headphones", category: "Electronics", price: 3300, quantity: 0, code: "WH" },
  { id: 3, name: "Smart Watch", category: "Electronics", price: 5700, quantity: 12, code: "SW" },
  { id: 4, name: "Bluetooth Speaker", category: "Electronics", price: 8100, quantity: 15, code: "BS" },
  { id: 5, name: "Wireless Mouse", category: "Electronics", price: 10500, quantity: 18, code: "WM" },
  { id: 6, name: "Mechanical Keyboard", category: "Electronics", price: 12900, quantity: 21, code: "MK" },
  { id: 7, name: "Tablet", category: "Electronics", price: 15300, quantity: 24, code: "T" },
  { id: 8, name: "Power Bank", category: "Electronics", price: 17700, quantity: 1, code: "PB" },
  { id: 9, name: "USB-C Hub", category: "Electronics", price: 20100, quantity: 4, code: "UH" },
  { id: 10, name: "Web Camera", category: "Electronics", price: 22500, quantity: 7, code: "WC" },
  { id: 11, name: "Portable SSD", category: "Electronics", price: 24900, quantity: 10, code: "PS" },
  { id: 12, name: "Gaming Monitor", category: "Electronics", price: 27300, quantity: 13, code: "GM" },
  { id: 13, name: "Earbuds", category: "Electronics", price: 29700, quantity: 16, code: "E" },
  { id: 14, name: "Phone Stand", category: "Electronics", price: 32100, quantity: 0, code: "PS" },
  { id: 15, name: "Wireless Charger", category: "Electronics", price: 34500, quantity: 22, code: "WC" },
  { id: 16, name: "Digital Camera", category: "Electronics", price: 36900, quantity: 25, code: "DC" },
  { id: 17, name: "Smartphone", category: "Electronics", price: 39300, quantity: 2, code: "S" },
  { id: 18, name: "Mini Projector", category: "Electronics", price: 41700, quantity: 5, code: "MP" },
  { id: 19, name: "WiFi Router", category: "Electronics", price: 44100, quantity: 8, code: "WR" },
  { id: 20, name: "Desk Microphone", category: "Electronics", price: 46500, quantity: 0, code: "DM" },
  { id: 21, name: "Essential T-Shirt", category: "Clothing", price: 600, quantity: 6, code: "ET" },
  { id: 22, name: "Classic Jeans", category: "Clothing", price: 740, quantity: 0, code: "CJ" },
  { id: 23, name: "Cotton Shirt", category: "Clothing", price: 880, quantity: 12, code: "CS" },
  { id: 24, name: "Formal Trousers", category: "Clothing", price: 1020, quantity: 15, code: "FT" },
  { id: 25, name: "Oversized Hoodie", category: "Clothing", price: 1160, quantity: 18, code: "OH" },
  { id: 26, name: "Denim Jacket", category: "Clothing", price: 1300, quantity: 21, code: "DJ" },
  { id: 27, name: "Linen Shirt", category: "Clothing", price: 1440, quantity: 24, code: "LS" },
  { id: 28, name: "Cargo Pants", category: "Clothing", price: 1580, quantity: 1, code: "CP" },
  { id: 29, name: "Crewneck Sweatshirt", category: "Clothing", price: 1720, quantity: 4, code: "CS" },
  { id: 30, name: "Polo T-Shirt", category: "Clothing", price: 1860, quantity: 7, code: "PT" },
  { id: 31, name: "Casual Shorts", category: "Clothing", price: 2000, quantity: 10, code: "CS" },
  { id: 32, name: "Knit Sweater", category: "Clothing", price: 2140, quantity: 13, code: "KS" },
  { id: 33, name: "Long Coat", category: "Clothing", price: 2280, quantity: 16, code: "LC" },
  { id: 34, name: "Track Pants", category: "Clothing", price: 2420, quantity: 0, code: "TP" },
  { id: 35, name: "Basic Tank Top", category: "Clothing", price: 2560, quantity: 22, code: "BT" },
  { id: 36, name: "Pleated Skirt", category: "Clothing", price: 2700, quantity: 25, code: "PS" },
  { id: 37, name: "Cotton Dress", category: "Clothing", price: 2840, quantity: 2, code: "CD" },
  { id: 38, name: "Blazer", category: "Clothing", price: 2980, quantity: 5, code: "B" },
  { id: 39, name: "Cardigan", category: "Clothing", price: 3120, quantity: 8, code: "C" },
  { id: 40, name: "Relaxed Joggers", category: "Clothing", price: 3260, quantity: 0, code: "RJ" },
  { id: 41, name: "Premium Rice", category: "Grocery", price: 60, quantity: 6, code: "PR" },
  { id: 42, name: "Fresh Milk", category: "Grocery", price: 95, quantity: 0, code: "FM" },
  { id: 43, name: "Whole Wheat Bread", category: "Grocery", price: 130, quantity: 12, code: "WW" },
  { id: 44, name: "Brown Eggs", category: "Grocery", price: 165, quantity: 15, code: "BE" },
  { id: 45, name: "Ground Coffee", category: "Grocery", price: 200, quantity: 18, code: "GC" },
  { id: 46, name: "Green Tea", category: "Grocery", price: 235, quantity: 21, code: "GT" },
  { id: 47, name: "Olive Oil", category: "Grocery", price: 270, quantity: 24, code: "OO" },
  { id: 48, name: "Peanut Butter", category: "Grocery", price: 305, quantity: 1, code: "PB" },
  { id: 49, name: "Rolled Oats", category: "Grocery", price: 340, quantity: 4, code: "RO" },
  { id: 50, name: "Mixed Nuts", category: "Grocery", price: 375, quantity: 7, code: "MN" },
  { id: 51, name: "Dark Chocolate", category: "Grocery", price: 410, quantity: 10, code: "DC" },
  { id: 52, name: "Pasta", category: "Grocery", price: 445, quantity: 13, code: "P" },
  { id: 53, name: "Tomato Sauce", category: "Grocery", price: 480, quantity: 16, code: "TS" },
  { id: 54, name: "Breakfast Cereal", category: "Grocery", price: 515, quantity: 0, code: "BC" },
  { id: 55, name: "Fruit Juice", category: "Grocery", price: 550, quantity: 22, code: "FJ" },
  { id: 56, name: "Honey", category: "Grocery", price: 585, quantity: 25, code: "H" },
  { id: 57, name: "Cheddar Cheese", category: "Grocery", price: 620, quantity: 2, code: "CC" },
  { id: 58, name: "Greek Yogurt", category: "Grocery", price: 655, quantity: 5, code: "GY" },
  { id: 59, name: "Organic Flour", category: "Grocery", price: 690, quantity: 8, code: "OF" },
  { id: 60, name: "Sea Salt", category: "Grocery", price: 725, quantity: 0, code: "SS" },
  { id: 61, name: "Table Lamp", category: "Home & Living", price: 450, quantity: 6, code: "TL" },
  { id: 62, name: "Cotton Bedsheet", category: "Home & Living", price: 570, quantity: 0, code: "CB" },
  { id: 63, name: "Ceramic Vase", category: "Home & Living", price: 690, quantity: 12, code: "CV" },
  { id: 64, name: "Wall Clock", category: "Home & Living", price: 810, quantity: 15, code: "WC" },
  { id: 65, name: "Floor Lamp", category: "Home & Living", price: 930, quantity: 18, code: "FL" },
  { id: 66, name: "Cushion Set", category: "Home & Living", price: 1050, quantity: 21, code: "CS" },
  { id: 67, name: "Storage Basket", category: "Home & Living", price: 1170, quantity: 24, code: "SB" },
  { id: 68, name: "Scented Candle", category: "Home & Living", price: 1290, quantity: 1, code: "SC" },
  { id: 69, name: "Throw Blanket", category: "Home & Living", price: 1410, quantity: 4, code: "TB" },
  { id: 70, name: "Desk Organizer", category: "Home & Living", price: 1530, quantity: 7, code: "DO" },
  { id: 71, name: "Dinner Plate Set", category: "Home & Living", price: 1650, quantity: 10, code: "DP" },
  { id: 72, name: "Glass Tumbler Set", category: "Home & Living", price: 1770, quantity: 13, code: "GT" },
  { id: 73, name: "Bath Towel", category: "Home & Living", price: 1890, quantity: 16, code: "BT" },
  { id: 74, name: "Laundry Basket", category: "Home & Living", price: 2010, quantity: 0, code: "LB" },
  { id: 75, name: "Wall Mirror", category: "Home & Living", price: 2130, quantity: 22, code: "WM" },
  { id: 76, name: "Plant Pot", category: "Home & Living", price: 2250, quantity: 25, code: "PP" },
  { id: 77, name: "Cutlery Set", category: "Home & Living", price: 2370, quantity: 2, code: "CS" },
  { id: 78, name: "Serving Tray", category: "Home & Living", price: 2490, quantity: 5, code: "ST" },
  { id: 79, name: "Photo Frame", category: "Home & Living", price: 2610, quantity: 8, code: "PF" },
  { id: 80, name: "Door Mat", category: "Home & Living", price: 2730, quantity: 0, code: "DM" },
  { id: 81, name: "Face Cleanser", category: "Beauty", price: 250, quantity: 6, code: "FC" },
  { id: 82, name: "Daily Moisturizer", category: "Beauty", price: 335, quantity: 0, code: "DM" },
  { id: 83, name: "Sunscreen Lotion", category: "Beauty", price: 420, quantity: 12, code: "SL" },
  { id: 84, name: "Lip Balm", category: "Beauty", price: 505, quantity: 15, code: "LB" },
  { id: 85, name: "Body Lotion", category: "Beauty", price: 590, quantity: 18, code: "BL" },
  { id: 86, name: "Shampoo", category: "Beauty", price: 675, quantity: 21, code: "S" },
  { id: 87, name: "Conditioner", category: "Beauty", price: 760, quantity: 24, code: "C" },
  { id: 88, name: "Hair Serum", category: "Beauty", price: 845, quantity: 1, code: "HS" },
  { id: 89, name: "Hand Cream", category: "Beauty", price: 930, quantity: 4, code: "HC" },
  { id: 90, name: "Body Wash", category: "Beauty", price: 1015, quantity: 7, code: "BW" },
  { id: 91, name: "Face Serum", category: "Beauty", price: 1100, quantity: 10, code: "FS" },
  { id: 92, name: "Clay Mask", category: "Beauty", price: 1185, quantity: 13, code: "CM" },
  { id: 93, name: "Face Toner", category: "Beauty", price: 1270, quantity: 16, code: "FT" },
  { id: 94, name: "Hair Oil", category: "Beauty", price: 1355, quantity: 0, code: "HO" },
  { id: 95, name: "Perfume", category: "Beauty", price: 1440, quantity: 22, code: "P" },
  { id: 96, name: "Nail Care Set", category: "Beauty", price: 1525, quantity: 25, code: "NC" },
  { id: 97, name: "Bath Salts", category: "Beauty", price: 1610, quantity: 2, code: "BS" },
  { id: 98, name: "Body Scrub", category: "Beauty", price: 1695, quantity: 5, code: "BS" },
  { id: 99, name: "Face Mist", category: "Beauty", price: 1780, quantity: 8, code: "FM" },
  { id: 100, name: "Hair Mask", category: "Beauty", price: 1865, quantity: 0, code: "HM" },
  { id: 101, name: "Hardcover Notebook", category: "Books & Stationery", price: 120, quantity: 6, code: "HN" },
  { id: 102, name: "Gel Pen Set", category: "Books & Stationery", price: 165, quantity: 0, code: "GP" },
  { id: 103, name: "Weekly Planner", category: "Books & Stationery", price: 210, quantity: 12, code: "WP" },
  { id: 104, name: "Sketch Book", category: "Books & Stationery", price: 255, quantity: 15, code: "SB" },
  { id: 105, name: "Desk Calendar", category: "Books & Stationery", price: 300, quantity: 18, code: "DC" },
  { id: 106, name: "Marker Set", category: "Books & Stationery", price: 345, quantity: 21, code: "MS" },
  { id: 107, name: "Sticky Notes", category: "Books & Stationery", price: 390, quantity: 24, code: "SN" },
  { id: 108, name: "Pencil Case", category: "Books & Stationery", price: 435, quantity: 1, code: "PC" },
  { id: 109, name: "Drawing Pencils", category: "Books & Stationery", price: 480, quantity: 4, code: "DP" },
  { id: 110, name: "Acrylic Ruler", category: "Books & Stationery", price: 525, quantity: 7, code: "AR" },
  { id: 111, name: "Journal", category: "Books & Stationery", price: 570, quantity: 10, code: "J" },
  { id: 112, name: "Document Folder", category: "Books & Stationery", price: 615, quantity: 13, code: "DF" },
  { id: 113, name: "Fountain Pen", category: "Books & Stationery", price: 660, quantity: 16, code: "FP" },
  { id: 114, name: "Art Paper Set", category: "Books & Stationery", price: 705, quantity: 0, code: "AP" },
  { id: 115, name: "Index Cards", category: "Books & Stationery", price: 750, quantity: 22, code: "IC" },
  { id: 116, name: "Binder Clips", category: "Books & Stationery", price: 795, quantity: 25, code: "BC" },
  { id: 117, name: "Mechanical Pencil", category: "Books & Stationery", price: 840, quantity: 2, code: "MP" },
  { id: 118, name: "Reading Journal", category: "Books & Stationery", price: 885, quantity: 5, code: "RJ" },
  { id: 119, name: "Desk Notepad", category: "Books & Stationery", price: 930, quantity: 8, code: "DN" },
  { id: 120, name: "Book Stand", category: "Books & Stationery", price: 975, quantity: 0, code: "BS" }
];

export const categories = ["All","Electronics","Clothing","Grocery","Home & Living","Beauty","Books & Stationery"];
